apiVersion: networking.example.com/v1alpha1
kind: SidecarGenerator
metadata:
  labels:
    app.kubernetes.io/name: sidecar-generator-operator
    app.kubernetes.io/managed-by: kustomize
  name: sidecargenerator-sample
spec:
  url: "https://httpd-default.apps-crc.testing/dependencies"
  refreshPeriod: 2m
  insecureSkipTLSVerify: true
  workloadSelector:
    labels: 
      app: myapp
